#!/usr/bin/env python
n = raw_input('>>>')
n = int(n)

def fib(n):
    zahlen=[0, 1]
    if n < 2:
        return zahlen[n]
    for i in range(2, n + 1):
        #print i (Zaehler)
        zahlen.append(zahlen[-1] + zahlen[-2])
    return zahlen[n]    
print fib(n)

